site_name: Python Pipelines Demo

theme:
  name: material

plugins:
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src]
        options:
          allow_inspection: true